name: ehs_new
description: Monitor compliance

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  nb_utils:
  flutter_mobx:
  cached_network_image:
  flutter_svg:
  http:
  shared_preferences:
  provider:
  toggle_switch:
  expandable:
  multi_select_flutter:
  file_picker:
  simple_speed_dial:
  image_picker:
  geolocator:
  geocoding:
  flutter_typeahead:
  flutter_google_places:
  awesome_snackbar_content:
  sqflite:
  path_provider:
  background_fetch: any
  #connectivity:
  auto_size_text:
  permission_handler:
  flutter_keyboard_visibility: any
  logger: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #connectivity_plus: ^5.0.2
  get: ^4.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/background/bg.png
    - images/app/icons/app_icon.png
    - images/app/icons/ehs.svg
    - images/app/icons/logo.png
    - images/app/menu/actionbg.png
    - images/app/menu/auditsbg.png
    - images/app/menu/communicationbg.png
    - images/app/menu/incidentbg.png
    - images/app/menu/inspectionbg.png
    - images/app/menu/observationsbg.png
    - images/app/menu/surveysbg.png
    - images/app/menu/menus.png
    - images/app/icons/view.png
    - images/app/icons/user.png
    - images/app/icons/pencil.png
    - images/app/icons/delete.png
    - images/app/icons/bgGov1.png
    - images/app/icons/eshlogo.png
    - images/background/observations.png
    - images/app/menu/actions.png
    - images/app/menu/audits.png
    - images/app/menu/communications.png
    - images/app/menu/incidents.png
    - images/app/menu/inspections.png
    - images/app/menu/observations.png
    - images/app/menu/surveys.png
    - images/app/icons/deleteN.svg
    - images/app/icons/viewN.svg
    - images/app/icons/pencilN.svg
    - images/app/icons/upload.png
    - images/app/icons/mobiledata.svg
    - images/app/icons/wifi.svg
    - images/app/icons/login_logo.png
    - images/app/icons/User_tag.png
    - images/app/icons/Link_logo.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Bold.ttf
    #         style: italic
    - family: RocgroTesk
      fonts:
        - asset: fonts/Fontspring-DEMO-rocgrotesk-bold.otf
        - asset: fonts/Fontspring-DEMO-rocgrotesk-regular.otf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages